# TODO: Dockerfile pentru Database (PostgreSQL)
# Cerinte:
# 1. Foloseste imaginea postgres:15-alpine ca baza
# 2. Copiaza init.sql in /docker-entrypoint-initdb.d/ pentru initializare automata

# Scrie Dockerfile-ul aici:
